package com.linrun.interview.modules.knowledgebase.service.parse.mineru;

/** 可持久化、可观测且不包含敏感正文的 MinerU 失败分类。 */
public enum MineruFailureCode {
  DISABLED,
  CONFIGURATION,
  PUBLIC_URL_UNAVAILABLE,
  AUTHENTICATION,
  RATE_LIMITED,
  PROVIDER_5XX,
  PROVIDER_REJECTED,
  INVALID_RESPONSE,
  TASK_FAILED,
  TASK_TIMEOUT,
  RESULT_URL_REJECTED,
  RESULT_DOWNLOAD_FAILED,
  RESULT_TOO_LARGE,
  ZIP_SECURITY_VIOLATION,
  FULL_MD_MISSING,
  FALLBACK_FAILED,
  INTERRUPTED,
  UNKNOWN
}
