package com.linrun.interview.modules.github.security;

import com.linrun.interview.modules.github.model.GithubFileStatus;
import java.nio.ByteBuffer;
import java.nio.charset.CharacterCodingException;
import java.nio.charset.CodingErrorAction;
import java.nio.charset.StandardCharsets;
import java.util.Locale;
import org.springframework.stereotype.Component;

/** Blob 下载后的二次内容安全检查。 */
@Component
public class GithubContentInspector {

  private static final int MAX_CONTROL_SAMPLE = 8192;
  private final GithubSecretDetector secretDetector;

  public GithubContentInspector(GithubSecretDetector secretDetector) {
    this.secretDetector = secretDetector;
  }

  public InspectionResult inspect(String path, byte[] bytes) {
    if (bytes == null || bytes.length == 0) {
      return InspectionResult.accepted("");
    }
    if (looksBinary(bytes)) {
      return InspectionResult.rejected(
          GithubFileStatus.EXCLUDED_BINARY, "文件内容疑似二进制，未保存正文");
    }
    String content;
    try {
      content = StandardCharsets.UTF_8.newDecoder()
          .onMalformedInput(CodingErrorAction.REPORT)
          .onUnmappableCharacter(CodingErrorAction.REPORT)
          .decode(ByteBuffer.wrap(bytes))
          .toString();
    } catch (CharacterCodingException e) {
      return InspectionResult.rejected(
          GithubFileStatus.FETCH_FAILED, "文件不是有效 UTF-8，未保存正文");
    }
    if (secretDetector.containsLikelySecret(content)) {
      return InspectionResult.rejected(
          GithubFileStatus.SECRET_BLOCKED, "疑似包含密钥，正文未进入证据库");
    }
    if (looksGenerated(path, content)) {
      return InspectionResult.rejected(
          GithubFileStatus.EXCLUDED_GENERATED, "文件头标记为生成代码，未进入证据库");
    }
    return InspectionResult.accepted(normalizeNewlines(content));
  }

  private boolean looksBinary(byte[] bytes) {
    int sampled = Math.min(bytes.length, MAX_CONTROL_SAMPLE);
    int controls = 0;
    for (int index = 0; index < sampled; index++) {
      int value = bytes[index] & 0xff;
      if (value == 0) {
        return true;
      }
      if (value < 0x09 || (value > 0x0d && value < 0x20)) {
        controls++;
      }
    }
    return controls > Math.max(4, sampled / 50);
  }

  private boolean looksGenerated(String path, String content) {
    String header = content.substring(0, Math.min(1000, content.length()))
        .toLowerCase(Locale.ROOT);
    return header.contains("generated by")
        || header.contains("auto-generated")
        || header.contains("automatically generated")
        || header.contains("do not edit this file")
        || path.toLowerCase(Locale.ROOT).endsWith(".g.cs");
  }

  private String normalizeNewlines(String content) {
    return content.replace("\r\n", "\n").replace('\r', '\n');
  }

  public record InspectionResult(
      boolean accepted,
      String content,
      GithubFileStatus rejectionStatus,
      String reason
  ) {
    static InspectionResult accepted(String content) {
      return new InspectionResult(true, content, null, null);
    }

    static InspectionResult rejected(GithubFileStatus status, String reason) {
      return new InspectionResult(false, null, status, reason);
    }
  }
}
