-- 知识库三表重构（对齐 know-engine）：版本管理 + 分段表 + 文档主表状态字段
-- 配合 KnowledgeBaseEntity / KnowledgeBaseVersionEntity / KnowledgeBaseSegmentEntity
-- 列名采用蛇形（Spring Boot 默认 SpringPhysicalNamingStrategy：驼峰 -> 蛇形）

-- 1. 文档版本表
CREATE TABLE public.knowledge_base_version (
    version_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    doc_id bigint NOT NULL,
    version character varying(32) NOT NULL,
    doc_url character varying(1000),
    converted_doc_url character varying(1000),
    converted_content text,
    content_hash character varying(64),
    status character varying(20),
    upload_user character varying(64),
    changelog character varying(500),
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT knowledge_base_version_pkey PRIMARY KEY (version_id)
);

CREATE INDEX idx_kbv_doc_id        ON public.knowledge_base_version (doc_id);
CREATE INDEX idx_kbv_doc_version   ON public.knowledge_base_version (doc_id, version);

-- 2. 文档分段表
CREATE TABLE public.knowledge_base_segment (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    text text NOT NULL,
    chunk_id character varying(64),
    metadata text,
    document_id bigint NOT NULL,
    document_version bigint NOT NULL,
    chunk_order integer,
    embedding_id character varying(128),
    status character varying(20),
    skip_embedding integer DEFAULT 0,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT knowledge_base_segment_pkey PRIMARY KEY (id)
);

CREATE INDEX idx_kbs_doc_version ON public.knowledge_base_segment (document_id, document_version);
CREATE INDEX idx_kbs_status      ON public.knowledge_base_segment (status);

-- 3. 文档主表新增字段（过渡期与旧 vector_status/chunk_count 共存，后续清理）
ALTER TABLE public.knowledge_bases ADD COLUMN IF NOT EXISTS current_version_id bigint;
ALTER TABLE public.knowledge_bases ADD COLUMN IF NOT EXISTS description character varying(500);
ALTER TABLE public.knowledge_bases ADD COLUMN IF NOT EXISTS doc_status character varying(20);
