package com.linrun.interview.github.security;

import static org.assertj.core.api.Assertions.assertThat;

import com.linrun.interview.github.client.GithubPublicApiClient.TreeEntry;
import com.linrun.interview.github.config.GithubEvidenceProperties;
import com.linrun.interview.github.model.GithubFileKind;
import com.linrun.interview.github.model.GithubFileStatus;
import java.nio.charset.StandardCharsets;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

@DisplayName("GitHub 文件与正文安全策略")
class GithubFilePolicyTest {

  private static final String SHA = "a".repeat(40);
  private GithubEvidenceProperties properties;
  private GithubFilePolicy filePolicy;
  private GithubContentInspector inspector;

  @BeforeEach
  void setUp() {
    properties = new GithubEvidenceProperties();
    GithubSecretDetector detector = new GithubSecretDetector();
    filePolicy = new GithubFilePolicy(properties, detector);
    inspector = new GithubContentInspector(detector);
  }

  @Test
  @DisplayName("纳入源码、测试和依赖声明，排除依赖目录、产物、敏感与二进制")
  void shouldBuildSafeManifest() {
    assertThat(decision("src/main/java/demo/App.java", 100).status())
        .isEqualTo(GithubFileStatus.ELIGIBLE);
    assertThat(decision("src/test/java/demo/AppTest.java", 100).kind())
        .isEqualTo(GithubFileKind.TEST);
    assertThat(decision("pom.xml", 100).kind()).isEqualTo(GithubFileKind.BUILD);
    assertThat(decision("node_modules/pkg/index.js", 100).status())
        .isEqualTo(GithubFileStatus.EXCLUDED_DEPENDENCY);
    assertThat(decision("backend/target/App.class", 100).status())
        .isEqualTo(GithubFileStatus.EXCLUDED_BUILD_OUTPUT);
    assertThat(decision(".env", 100).status())
        .isEqualTo(GithubFileStatus.EXCLUDED_SENSITIVE_PATH);
    assertThat(decision("docs/logo.png", 100).status())
        .isEqualTo(GithubFileStatus.EXCLUDED_BINARY);
    assertThat(decision("src/generated/Api.java", 100).status())
        .isEqualTo(GithubFileStatus.EXCLUDED_GENERATED);
  }

  @Test
  @DisplayName("超大文件与非法 Blob SHA 不进入可选清单")
  void shouldRejectOversizedAndInvalidSha() {
    assertThat(decision("src/App.java", properties.getMaxFileBytes() + 1).status())
        .isEqualTo(GithubFileStatus.EXCLUDED_TOO_LARGE);
    assertThat(filePolicy.classify(new TreeEntry("src/App.java", "blob", "bad", 20)).status())
        .isEqualTo(GithubFileStatus.EXCLUDED_INVALID_PATH);
  }

  @Test
  @DisplayName("正文二次检查阻断密钥、二进制、生成代码和非法编码")
  void shouldRejectUnsafeContent() {
    assertThat(inspector.inspect("App.java",
        "password = \"this-is-a-real-secret-value\"".getBytes(StandardCharsets.UTF_8))
        .rejectionStatus()).isEqualTo(GithubFileStatus.SECRET_BLOCKED);
    assertThat(inspector.inspect("App.java", new byte[] {'a', 0, 'b'}).rejectionStatus())
        .isEqualTo(GithubFileStatus.EXCLUDED_BINARY);
    assertThat(inspector.inspect("Api.java",
        "// AUTO-GENERATED - do not edit this file\nclass Api {}"
            .getBytes(StandardCharsets.UTF_8)).rejectionStatus())
        .isEqualTo(GithubFileStatus.EXCLUDED_GENERATED);
    assertThat(inspector.inspect("App.java", new byte[] {(byte) 0xc3, (byte) 0x28})
        .rejectionStatus()).isEqualTo(GithubFileStatus.FETCH_FAILED);
  }

  @Test
  @DisplayName("安全 UTF-8 文本规范化换行后通过")
  void shouldAcceptSafeUtf8() {
    GithubContentInspector.InspectionResult result = inspector.inspect(
        "src/App.java", "class App {\r\n}\r\n".getBytes(StandardCharsets.UTF_8));

    assertThat(result.accepted()).isTrue();
    assertThat(result.content()).isEqualTo("class App {\n}\n");
  }

  private com.linrun.interview.github.model.GithubFileDecision decision(
      String path,
      long size
  ) {
    return filePolicy.classify(new TreeEntry(path, "blob", SHA, size));
  }
}
